apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-business-processor
  namespace: products
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0-34
  instances: 1
  storage:
    size: 25Gi
  
  # bootstrap:
  #     recovery:
  #       source: clusterBackup
  #       database: app
  
  # externalClusters:
  #   - name: clusterBackup
  #     barmanObjectStore:
  #       destinationPath: "s3://dc1-database-backups"
  #       serverName: "business-processor-pg-cluster-17-2025-05-13"
  #       s3Credentials:
  #         accessKeyId:
  #           name: database-backup-aws-credentials
  #           key: accessKey
  #         secretAccessKey:
  #           name: database-backup-aws-credentials
  #           key: secretKey
  #       wal:
  #         maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: "s3://dc1-database-backups"
      serverName: "business-processor-pg-production"
      s3Credentials:
        accessKeyId:
          name: database-backup-aws-credentials
          key: accessKey
        secretAccessKey:
          name: database-backup-aws-credentials
          key: secretKey
      wal:
        compression: gzip
      data:
        compression: gzip
