apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases/couchdb

nameSuffix: -ap1 # Results in HelmRelease metadata.name: couchdb-base-main-dev

# Common settings for this specific HelmRelease instance
# Namespace for the HelmRelease CR itself and where CouchDB will be deployed.
# This kustomization is expected to be included by a higher-level kustomization
# that already sets the namespace, or this can set it directly.
# For this example, we assume the parent (my-app-namespace-dev/kustomization.yaml) sets it.

patches:
  - patch: |-
      # Patch the HelmRelease resource
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: couchdb # Kustomize targets by base name before suffix
      spec:
        targetNamespace: products # Explicitly set target for clarity
        values:
          clusterSize: 1
          # adminPasswordSecretRef: couchdb-main-dev-secret # Example for production
          couchdbConfig:
            couchdb:
              uuid: 8a50b1b7327546b085ee0b3eff8542cf # Replace with actual unique UUID
          persistentVolume:
            size: "5Gi"
    target:
      kind: HelmRelease
      name: couchdb
